pluginManagement {
    repositories {
        maven {
            name = 'Fabric'
            url = 'https://maven.fabricmc.net/'
        }
        mavenCentral()
        gradlePluginPortal()
    }
}

rootProject.name = 'authme-fabric'
include 'authme-core'
include 'authme-fabric'
include 'authme-fabric-mid'
include 'authme-fabric-legacy'
include 'authme-fabric-old'
include 'authme-fabric-pre'
include 'authme-fabric-older'
