package io.github.authme.fabric.auth;

import java.util.UUID;

/**
 * In-memory per-player session state held between login events. Pure data — no platform types.
 */
public final class PlayerSession {

    public final UUID uuid;
    public final String name;
    public boolean registered;
    public boolean authenticated;
    public boolean premium;
    public boolean pendingTotp;
    /** True while a native login/register/TOTP dialog is currently shown to the client. */
    public boolean dialogShown;
    /** Set after the asynchronous account lookup has classified this join. */
    public boolean accountResolved;
    public boolean captchaPending;
    public String captchaCode = "";
    public int loginAttempts;
    public long joinTime;
    public String lastIp;
    public long lastLogin;
    public String totpKey = "";
    /** Secret generated by /totp add and persisted only after /totp confirm succeeds. */
    public String pendingTotpSetupKey = "";
    public boolean invulnerableFrozen;
    /** Set to false before removing the session so late asynchronous DB callbacks cannot log it in. */
    public volatile boolean active = true;
    public long loginGeneration;
    public double frozenX, frozenY, frozenZ;
    public String frozenWorld;

    public PlayerSession(UUID uuid, String name) {
        this.uuid = uuid;
        this.name = name;
    }

    public boolean isUnauthenticated() {
        return !authenticated;
    }

    public boolean needsTotp() {
        return pendingTotp;
    }
}
