package io.github.authme.fabric.auth;

import io.github.authme.fabric.util.PermissionBridge;

import java.util.UUID;

/**
 * In-memory per-player session state held between login events. Pure data — no platform types.
 */
public final class PlayerSession {

    public final UUID uuid;
    public final String name;
    public boolean registered;
    public boolean authenticated;
    public boolean premium;
    public boolean pendingTotp;
    /** True when the pending TOTP challenge was entered through a proxy auto-login. */
    public boolean proxyTotpPending;
    /** True while a native login/register/TOTP dialog is currently shown to the client. */
    public boolean dialogShown;
    /** Set after the asynchronous account lookup has classified this join. */
    public boolean accountResolved;
    /**
     * True while one authentication-changing operation is waiting on the database.
     * Command handlers run on the server thread, while the actual database work runs
     * asynchronously; this flag prevents duplicate login/register/recovery requests
     * from racing each other for the same session.
     */
    public volatile boolean authenticationBusy;
    public boolean captchaPending;
    public String captchaCode = "";
    public int loginAttempts;
    /** Failed TOTP submissions for this connection; kept separate from password failures. */
    public int totpAttempts;
    /** Short per-connection backoff after repeated TOTP failures. */
    public long totpBlockedUntil;
    public long joinTime;
    public String lastIp;
    public long lastLogin;
    public String totpKey = "";
    /** Secret generated by /totp add and persisted only after /totp confirm succeeds. */
    public String pendingTotpSetupKey = "";
    public boolean invulnerableFrozen;
    /** Original vanilla ability state captured before entering AuthMe limbo. */
    public boolean limboCaptured;
    public boolean originalOperator;
    public boolean originalMayFly;
    public boolean originalFlying;
    public float originalWalkingSpeed = 0.1f;
    public float originalFlyingSpeed = 0.05f;
    public boolean originalInvulnerable;
    /** True only when AuthMe itself added the blindness effect and may remove it later. */
    public boolean authMeBlindEffect;
    /** True for a configured UnrestrictedName identity; it must not mutate a real account row. */
    public boolean unrestrictedName;
    public PermissionBridge.GroupSnapshot groupSnapshot;
    /** Set to false before removing the session so late asynchronous DB callbacks cannot log it in. */
    public volatile boolean active = true;
    public long loginGeneration;
    /** Prevents overlapping cross-instance login-fence reads. */
    public volatile boolean loginLeaseCheckInFlight;
    public double frozenX, frozenY, frozenZ;
    public String frozenWorld;

    public PlayerSession(UUID uuid, String name) {
        this.uuid = uuid;
        this.name = name;
    }

    public boolean isUnauthenticated() {
        return !authenticated;
    }

    public boolean needsTotp() {
        return pendingTotp;
    }
}
